spring.application.name=demo
server.port=8080

# ML Service base URL
app.ml.base-url=http://localhost:8000

# RestTemplate timeout (ms)
app.ml.connect-timeout=5000
app.ml.read-timeout=15000
spring.jackson.property-naming-strategy=SNAKE_CASE