spring.application.name=demo
server.port=8080

# ML Service base URL
app.ml.base-url=http://localhost:8000

# RestTemplate timeout (ms)
app.ml.connect-timeout=5000
app.ml.read-timeout=15000
spring.jackson.property-naming-strategy=SNAKE_CASE

spring.datasource.url=jdbc:mysql://localhost:3306/safenet_fraud?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=pass@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
